{
  ### Environment Parameters
  debug: false,
  mode: inference,
  cuda: true,
  pin_memory: true,
  wandb: false,
  worker: 0,
  CUDA_VISIBLE_DEVICES: '1',

  ### Train Parameters
  model_name: 'MyModel_modify',
    n_classes: 1,
    in_channels: 3,
    base_c: 64,
  inference_mode: 'segmentation',
  task: 'segmentation',
  dataloader: 'Image2Image_zero_pad',
  criterion: 'DiceBCE',
  input_space: 'RGB',
  input_channel: 3,
  input_size: [608, 608],  # DRIVE:608, STARE:704, CHASE_DB1:1024, HRF: 1344

  model_path: 'exp/DCEDAF-Net/2025-04-14 015351/MyModel_modify-Epoch_2186-f1_score_0.832594694653013.pt',
  val_x_path:   'datasets/DRIVE/val/input',
  val_y_path:   'datasets/DRIVE/val/label',
}
